#!/usr/bin/env bash
# fixing the symbolic link file
printf %s "
server {
        listen 80 default_server;
        listen [::]:80 default_server ipv6only=on;

        root /usr/share/nginx/html;
        index index.html index.htm;

        server_name localhost;

        location / {
                try_files $uri $uri/ =404;
        }

}
" > /etc/nginx/sites-enabled/default
pkill nginx
service nginx restart
