#!/usr/bin/env bash
#Loop that displays in the screen a iconic phrase
c=0
touch /var/run/holbertonscript.pid
while ((c<1))
do
trap "echo I hate the kill command" TERM
trap "echo Y U no love me?!" INT
trap "rm /var/run/holbertonscript.pid" QUIT TERM
echo "To infinity and beyond"
sleep 2
done
