#!/usr/bin/env bash
#Prints Holberton School 10 times but in the 4th time and 8th time changes the output
i=1
while [ $i -le 10 ]
do
    if [ $i -eq 4 ]
    then
	echo "bad luck"
    elif [ $i -eq 8 ]
    then
        echo "good luck"
    else
	echo "Holberton School"
    fi
    ((i++))
done
