#!/usr/bin/env bash
#Print from 1 to 20 but changes in some cases
i=1
while [ $i -le 20 ]
do
    echo "$i"
    case $i in
    4)
	echo "bad luck from China"
    ;;

    9)
        echo "bad luck from Japan"
    ;;

    17)
	echo "bad luck from Italy"
    ;;
    esac
    ((i++))
done
