#!/usr/bin/env bash
#Prints Holberton School 10 times but in the 4th time and 8th time changes the output
i=1
h=0
while [ $h -le 12 ]
do
    echo "Hour: $h"
    while [ $i -le 59 ]
    do
	echo "$i"
	((i++))
    done
    ((i=1))
    ((h++))
done
