#!/usr/bin/env bash
#Check if holbertonschool file exsist
if test -e "holbertonschool"
then
    echo "holbertonschool file exists"
    if test -s "holbertonschool"
    then
	echo "holbertonschool file is not empty"
	if test -f "holbertonschool"
	then
	    echo "holbertonschool is a regular file"
	    fi
    else
	echo "holbertonschool file is empty"
    fi
else
    echo "holbertonschool file does not exist"
fi
