#!/usr/bin/env bash
#script that configures an Ubuntu server with some requirements
cp /etc/hosts ~/hosts.new
sed 's/127.0.0.1/127.0.0.2/' -i ~/hosts.new
sed '$ a\8.8.8.8 facebook.com' -i ~/hosts.new
cp -f ~/hosts.new /etc/hosts
